name: "Check site submission"
description: "Check that the site submission is indeed a site submission"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
runs:
  using: "node16"
  main: "index.js"
