name: Site Submission
description: Submit a new personal site
title: "[Site]: "
labels: ["site", "triage"]
assignees:
  - max
body:
  - type: input
    id: url
    attributes:
      label: Site URL
      description: The URL of your personal site.
      placeholder: ex. https://max.dev
    validations:
      required: true
