name: Site Submission
description: Submit a new personal site to the directory.
title: "[Site]: "
labels: ["site", "triage"]
assignees:
  - max
body:
  - type: input
    id: url
    attributes:
      label: Site URL
      description: The URL of your personal site.
      placeholder: https://brianlovin.com/
    validations:
      required: true
