name: Create PR from site submission issue

on:
  issues:
    types: [labeled]

jobs:
  create-pr:
    if: github.event.label.name == 'site-submission'
    runs-on: ubuntu-latest
    steps:
      - name: Check site submission issue
        uses: actions/github-script@v5
        with:
          script: |
            const { URL } = require('url');
            const body = context.payload.issue.body;
            const url = new URL(body.split('### Site URL\n\n')[1]);
            console log(url);
