on:
  issues:
    types: [labeled]

jobs:
  create-pr:
    if: github.event.label.name == 'site-submission'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stefanbuck/github-issue-praser@v2
        id: site-submission-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/site-submission.yml
      # - run: echo '${{ steps.site-submission-parser.outputs.jsonString }}' > site.json
      # - run: cat site.json
